MVC/Controllers/CollectionManagementController.cs
using AutoMapper;
using MVC.ViewModels;
using ZephirCollection.Application.Interface;
using ZephirCollection.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class CollectionManagementController : Controller
    {
        private readonly ICardAppService _cardAppService;
        private readonly IRarityAppService _rarityAppService;
        private readonly ICollectionAppService _collectionAppService;
        private readonly ICollectorAppService _collectorAppService;

        public CollectionManagementController(
            ICardAppService cardAppService,
            IRarityAppService rarityAppService,
            ICollectionAppService collectionAppService,
            ICollectorAppService collectorAppService)
        {
            _cardAppService = cardAppService;
            _rarityAppService = rarityAppService;
            _collectionAppService = collectionAppService;
            _collectorAppService = collectorAppService;
        }

        public ActionResult Index()
        {
            var collectionManagement = new List<CollectionManagementViewModel>();

            var cards = _cardAppService.GetAll();
            var rarity = _rarityAppService.GetAll();
            var collection = _collectionAppService.GetAll();
            var collector = _collectorAppService.GetAll();

            foreach (var card in cards)
            {
                collectionManagement.Add(new CollectionManagementViewModel
                {
                    CardDescription = card.Description,
                    CardNumber = card.CardNumber,
                    CollectionDescription = collection.FirstOrDefault(s => s.CollectionId == card.CollectionId).Description,
                    RarityAbbreviation = rarity.FirstOrDefault(s => s.RarityId == card.RarityId).Abbreviation,
                });
            }
            
            return View(collectionManagement);
        }
    }
}

MVC/Controllers/PokemonCardListTestController.cs
using AutoMapper;
using MVC.ViewModels;
using ZephirCollection.Application.Interface;
using ZephirCollection.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class PokemonCardListTestController : Controller
    {
        //Faltam os serviços
        private readonly IPokemonCardListTestAppService _pokemonCardListTestAppService;

        public PokemonCardListTestController(IPokemonCardListTestAppService pokemonCardListTestAppService)
        {
            _pokemonCardListTestAppService = pokemonCardListTestAppService;
        }

        public ActionResult Index()
        {
            var pokemonCardListTestViewModel = Mapper.Map<IEnumerable<PokemonCard>, IEnumerable<PokemonCardListTestViewModel>>(_pokemonCardListTestAppService.GetAllPokemonCardList().ToList());

            var collectionListTestViewModel = Mapper.Map<IEnumerable<PokemonCard>, IEnumerable<PokemonCardListTestViewModel>>(_pokemonCardListTestAppService.GetAllPokemonCardList().ToList());

            return View(pokemonCardListTestViewModel);
        }
	}
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Clientes", "Index", "Clientes")</li>
                    <li>@Html.ActionLink("Produtos", "Index", "Produtos")</li>
                    <li>@Html.ActionLink("Card List Test", "Index", "PokemonCardListTest")</li>
                    <li>@Html.ActionLink("Collection", "Index", "CollectionManagement")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>